import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./provider";

const red_hat_display = Red_Hat_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={red_hat_display.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
